version: '3.1'
services:
        postgres-db:
                image: postgres
                restart: always
                environment: 
                        POSTGRES_PASSWORD: admin
                ports: 
                        - 5432:5432
        postgres-admin:
                image: adminer
                restart: always
                ports:
                        - 8082:8080
networks:
        compose-network:
                driver: bridge